name: Security Scan

on:
  push:
    branches:
      - '*'
permissions:
  contents: read
  security-events: write

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit # Instala o bandit junto com as outras dependências
  

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          limit-serverities-for-sarif: false
          output: 'trivy-results.sarif'

      - name: Upload Trivy SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Run Bandit (debug)
        run:
          bandit -r . || true

      - name: Run Bandit (SARIF)
        run: |
          bandit -r . -f json -o bandit.json || true 
      
      - name: Convert Bandit JSON to SARIF
        run: |
          python scripts/bandit_to_sarif.py
      - name: Upload Bandit SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-results.sarif
        env:
          SECRET_KEY: ${{ secrets.DJANGO_PROD_SECRET_KEY }}

